### ISSUE TITLE
Suggested changes for index.html

### ISSUE THREAD

**Issue by ReneMalingre** [ReneMalingre/Group-2-Whiskers-of-Zen#39]
Hey Lauren, I've thrown some screenshots of the landing page with some suggestions to improve layout and functionality. Let me know what you think?

**Comment by ReneMalingre** [comment]
![Image](https://user-images.githubusercontent.com/5469099/235049578-d3497118-d33f-4e9c-bf98-3a46c9d9b343.png)



![Image](https://user-images.githubusercontent.com/5469099/235049590-a17687ac-3182-40d8-9bb0-2c11121c6d17.png)



![Image](https://user-images.githubusercontent.com/5469099/235049597-eb24a55f-94ea-48bc-ba3c-0e189fe7fa13.png)

**Comment by gh120515** [comment]
Just updated, will be doing a PR :)
